language: android

jdk:
- openjdk7
- oraclejdk7
- oraclejdk8

android:
  components:
  - platform-tools
  - tools
  - build-tools-23.0.2
  - android-23
  - android-16
  - extra

script:
- "./gradlew assemblealpha_flavor_Debug assemblealpha_flavor_Release"

before_install:
- "git clone https://bitbucket.org/librepilot/librepilot.git && cd librepilot && git checkout next && make uavobjects && ./build/uavobjgenerator/uavobjgenerator && cd .."

sudo: required
env:
  global:
    MALLOC_ARENA_MAX=2
