language: android

jdk:
- oraclejdk8

android:
  components:
  - platform-tools
  - tools
  - build-tools-24.0.0
  - android-24
  - extra

script:
- "./gradlew assemblealpha_flavor_Debug assemblealpha_flavor_Release assemblebeta_flavor_Debug assemblebeta_flavor_Release assemblerelease_flavor_Debug assemblerelease_flavor_Release"

before_install:

sudo: required
env:
  global:
    MALLOC_ARENA_MAX=2
